// Code generated by protoc-gen-go. DO NOT EDIT.
// source: models.proto

package social

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status struct {
	Data                 int32    `protobuf:"varint,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{0}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetData() int32 {
	if m != nil {
		return m.Data
	}
	return 0
}

type PostMsg struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Message              string               `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	PostID               string               `protobuf:"bytes,3,opt,name=PostID,proto3" json:"PostID,omitempty"`
	Username             string               `protobuf:"bytes,4,opt,name=Username,proto3" json:"Username,omitempty"`
	Status               int32                `protobuf:"varint,5,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PostMsg) Reset()         { *m = PostMsg{} }
func (m *PostMsg) String() string { return proto.CompactTextString(m) }
func (*PostMsg) ProtoMessage()    {}
func (*PostMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{1}
}

func (m *PostMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostMsg.Unmarshal(m, b)
}
func (m *PostMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostMsg.Marshal(b, m, deterministic)
}
func (m *PostMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostMsg.Merge(m, src)
}
func (m *PostMsg) XXX_Size() int {
	return xxx_messageInfo_PostMsg.Size(m)
}
func (m *PostMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PostMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PostMsg proto.InternalMessageInfo

func (m *PostMsg) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *PostMsg) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *PostMsg) GetPostID() string {
	if m != nil {
		return m.PostID
	}
	return ""
}

func (m *PostMsg) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *PostMsg) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type FollowMapMsg struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Follower             string   `protobuf:"bytes,2,opt,name=Follower,proto3" json:"Follower,omitempty"`
	Status               bool     `protobuf:"varint,3,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FollowMapMsg) Reset()         { *m = FollowMapMsg{} }
func (m *FollowMapMsg) String() string { return proto.CompactTextString(m) }
func (*FollowMapMsg) ProtoMessage()    {}
func (*FollowMapMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{2}
}

func (m *FollowMapMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowMapMsg.Unmarshal(m, b)
}
func (m *FollowMapMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowMapMsg.Marshal(b, m, deterministic)
}
func (m *FollowMapMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowMapMsg.Merge(m, src)
}
func (m *FollowMapMsg) XXX_Size() int {
	return xxx_messageInfo_FollowMapMsg.Size(m)
}
func (m *FollowMapMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowMapMsg.DiscardUnknown(m)
}

var xxx_messageInfo_FollowMapMsg proto.InternalMessageInfo

func (m *FollowMapMsg) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *FollowMapMsg) GetFollower() string {
	if m != nil {
		return m.Follower
	}
	return ""
}

func (m *FollowMapMsg) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type FeedRequestMsg struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	FromPage             int32    `protobuf:"varint,2,opt,name=FromPage,proto3" json:"FromPage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeedRequestMsg) Reset()         { *m = FeedRequestMsg{} }
func (m *FeedRequestMsg) String() string { return proto.CompactTextString(m) }
func (*FeedRequestMsg) ProtoMessage()    {}
func (*FeedRequestMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{3}
}

func (m *FeedRequestMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedRequestMsg.Unmarshal(m, b)
}
func (m *FeedRequestMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedRequestMsg.Marshal(b, m, deterministic)
}
func (m *FeedRequestMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedRequestMsg.Merge(m, src)
}
func (m *FeedRequestMsg) XXX_Size() int {
	return xxx_messageInfo_FeedRequestMsg.Size(m)
}
func (m *FeedRequestMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedRequestMsg.DiscardUnknown(m)
}

var xxx_messageInfo_FeedRequestMsg proto.InternalMessageInfo

func (m *FeedRequestMsg) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *FeedRequestMsg) GetFromPage() int32 {
	if m != nil {
		return m.FromPage
	}
	return 0
}

type PostMsg2 struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Message              string               `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	PostID               string               `protobuf:"bytes,3,opt,name=PostID,proto3" json:"PostID,omitempty"`
	Username             string               `protobuf:"bytes,4,opt,name=Username,proto3" json:"Username,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PostMsg2) Reset()         { *m = PostMsg2{} }
func (m *PostMsg2) String() string { return proto.CompactTextString(m) }
func (*PostMsg2) ProtoMessage()    {}
func (*PostMsg2) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{4}
}

func (m *PostMsg2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostMsg2.Unmarshal(m, b)
}
func (m *PostMsg2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostMsg2.Marshal(b, m, deterministic)
}
func (m *PostMsg2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostMsg2.Merge(m, src)
}
func (m *PostMsg2) XXX_Size() int {
	return xxx_messageInfo_PostMsg2.Size(m)
}
func (m *PostMsg2) XXX_DiscardUnknown() {
	xxx_messageInfo_PostMsg2.DiscardUnknown(m)
}

var xxx_messageInfo_PostMsg2 proto.InternalMessageInfo

func (m *PostMsg2) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *PostMsg2) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *PostMsg2) GetPostID() string {
	if m != nil {
		return m.PostID
	}
	return ""
}

func (m *PostMsg2) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type ListOfPosts struct {
	Value                []*PostMsg `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
	Status               int32      `protobuf:"varint,2,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListOfPosts) Reset()         { *m = ListOfPosts{} }
func (m *ListOfPosts) String() string { return proto.CompactTextString(m) }
func (*ListOfPosts) ProtoMessage()    {}
func (*ListOfPosts) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{5}
}

func (m *ListOfPosts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOfPosts.Unmarshal(m, b)
}
func (m *ListOfPosts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOfPosts.Marshal(b, m, deterministic)
}
func (m *ListOfPosts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOfPosts.Merge(m, src)
}
func (m *ListOfPosts) XXX_Size() int {
	return xxx_messageInfo_ListOfPosts.Size(m)
}
func (m *ListOfPosts) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOfPosts.DiscardUnknown(m)
}

var xxx_messageInfo_ListOfPosts proto.InternalMessageInfo

func (m *ListOfPosts) GetValue() []*PostMsg {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ListOfPosts) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func init() {
	proto.RegisterType((*Status)(nil), "socialpb.Status")
	proto.RegisterType((*PostMsg)(nil), "socialpb.PostMsg")
	proto.RegisterType((*FollowMapMsg)(nil), "socialpb.FollowMapMsg")
	proto.RegisterType((*FeedRequestMsg)(nil), "socialpb.FeedRequestMsg")
	proto.RegisterType((*PostMsg2)(nil), "socialpb.PostMsg2")
	proto.RegisterType((*ListOfPosts)(nil), "socialpb.ListOfPosts")
}

func init() {
	proto.RegisterFile("models.proto", fileDescriptor_0b5431a010549573)
}

var fileDescriptor_0b5431a010549573 = []byte{
	// 416 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x92, 0xcf, 0xaa, 0xd3, 0x40,
	0x14, 0xc6, 0x6f, 0x7a, 0x6f, 0x7a, 0xd3, 0xd3, 0x2a, 0x75, 0xc0, 0x12, 0x82, 0x60, 0xc9, 0xc6,
	0xae, 0x52, 0x48, 0x5d, 0xb8, 0x14, 0xac, 0x45, 0xc1, 0x6a, 0x49, 0xad, 0x4b, 0x61, 0xda, 0x9c,
	0x86, 0xc0, 0xa4, 0x13, 0x33, 0x93, 0xf6, 0x3d, 0x7c, 0x0b, 0x5f, 0xc5, 0xa7, 0x92, 0x99, 0xc9,
	0x3f, 0xad, 0x22, 0xb8, 0x72, 0x97, 0x33, 0xe7, 0x3b, 0xbf, 0x7c, 0xf3, 0xcd, 0x81, 0x51, 0xc6,
	0x63, 0x64, 0x22, 0xc8, 0x0b, 0x2e, 0x39, 0x71, 0x04, 0x3f, 0xa4, 0x94, 0xe5, 0x7b, 0xef, 0x69,
	0xc2, 0x79, 0xc2, 0x70, 0xae, 0xcf, 0xf7, 0xe5, 0x71, 0x2e, 0xd3, 0x0c, 0x85, 0xa4, 0x59, 0x6e,
	0xa4, 0xfe, 0x13, 0xe8, 0x6f, 0x25, 0x95, 0xa5, 0x20, 0x04, 0xee, 0x62, 0x2a, 0xa9, 0x6b, 0x4d,
	0xad, 0x99, 0x1d, 0xe9, 0x6f, 0xff, 0x9b, 0x05, 0xf7, 0x1b, 0x2e, 0xe4, 0x5a, 0x24, 0xe4, 0x05,
	0x0c, 0x3e, 0xd6, 0xc3, 0x5a, 0x34, 0x0c, 0xbd, 0xc0, 0xe0, 0x83, 0x1a, 0x1f, 0x34, 0x8a, 0xa8,
	0x15, 0x13, 0x17, 0xee, 0xd7, 0x28, 0x04, 0x4d, 0xd0, 0xed, 0x4d, 0xad, 0xd9, 0x20, 0xaa, 0x4b,
	0x32, 0x81, 0xbe, 0xc2, 0xbf, 0x5d, 0xba, 0xb7, 0xba, 0x51, 0x55, 0xc4, 0x03, 0x67, 0x27, 0xb0,
	0x38, 0xd1, 0x0c, 0xdd, 0x3b, 0xdd, 0x69, 0x6a, 0x35, 0x63, 0x1c, 0xbb, 0xb6, 0x76, 0x5a, 0x55,
	0xfe, 0x67, 0x18, 0xad, 0x38, 0x63, 0xfc, 0xb2, 0xa6, 0xb9, 0xf2, 0xdb, 0x65, 0x58, 0xbf, 0x30,
	0x3c, 0x70, 0x8c, 0x16, 0x8b, 0xca, 0x52, 0x53, 0x77, 0xf8, 0xca, 0x93, 0xd3, 0xf0, 0xdf, 0xc0,
	0xc3, 0x15, 0x62, 0x1c, 0xe1, 0x97, 0x12, 0x4d, 0x22, 0x7f, 0xfb, 0x43, 0xc1, 0xb3, 0x4d, 0x7d,
	0x69, 0x3b, 0x6a, 0x6a, 0xff, 0xab, 0x05, 0x4e, 0x95, 0x6a, 0xf8, 0xbf, 0xc4, 0xea, 0xbf, 0x87,
	0xe1, 0xbb, 0x54, 0xc8, 0x0f, 0x47, 0xa5, 0x15, 0xe4, 0x19, 0xd8, 0x67, 0xca, 0x4a, 0x75, 0xb1,
	0xdb, 0xd9, 0x30, 0x7c, 0x14, 0xd4, 0x2b, 0x15, 0x54, 0xce, 0x23, 0xd3, 0xef, 0xc4, 0xd5, 0xeb,
	0x3e, 0x47, 0xf8, 0xbd, 0x07, 0x0f, 0xb6, 0x7a, 0x66, 0x8b, 0xc5, 0x39, 0x3d, 0x20, 0x79, 0x0e,
	0xf0, 0xaa, 0x40, 0x2a, 0x51, 0x11, 0xc8, 0x35, 0xd1, 0xbb, 0x3e, 0xf2, 0x6f, 0xc8, 0x02, 0x60,
	0x89, 0x0c, 0xff, 0x3c, 0x35, 0x6e, 0x8f, 0xaa, 0x97, 0xba, 0x21, 0x2f, 0x81, 0xec, 0xf2, 0x98,
	0x4a, 0x34, 0xaf, 0x5a, 0x6d, 0xf8, 0xa4, 0x55, 0x76, 0x37, 0xe5, 0xb7, 0x84, 0xd7, 0x30, 0xfe,
	0x94, 0xe2, 0xc5, 0x18, 0x8e, 0x4d, 0x26, 0x6e, 0x67, 0xfe, 0xa7, 0x4d, 0xf0, 0x1e, 0xb7, 0x9d,
	0x4e, 0x88, 0x2d, 0x66, 0x83, 0x85, 0xe0, 0x27, 0xca, 0xd4, 0xd8, 0x3f, 0x60, 0xf6, 0x7d, 0xbd,
	0x09, 0x8b, 0x1f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x25, 0xa4, 0xc4, 0x2c, 0xe7, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SocialServiceClient is the client API for SocialService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SocialServiceClient interface {
	CreatePost(ctx context.Context, in *PostMsg, opts ...grpc.CallOption) (*PostMsg, error)
	DeletePost(ctx context.Context, in *PostMsg, opts ...grpc.CallOption) (*Status, error)
	UpdateFollowStatus(ctx context.Context, in *FollowMapMsg, opts ...grpc.CallOption) (*Status, error)
	ViewCreatedPosts(ctx context.Context, in *FeedRequestMsg, opts ...grpc.CallOption) (*ListOfPosts, error)
	ViewPersonalFeed(ctx context.Context, in *FeedRequestMsg, opts ...grpc.CallOption) (*ListOfPosts, error)
}

type socialServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSocialServiceClient(cc grpc.ClientConnInterface) SocialServiceClient {
	return &socialServiceClient{cc}
}

func (c *socialServiceClient) CreatePost(ctx context.Context, in *PostMsg, opts ...grpc.CallOption) (*PostMsg, error) {
	out := new(PostMsg)
	err := c.cc.Invoke(ctx, "/socialpb.SocialService/CreatePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) DeletePost(ctx context.Context, in *PostMsg, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/socialpb.SocialService/DeletePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) UpdateFollowStatus(ctx context.Context, in *FollowMapMsg, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/socialpb.SocialService/UpdateFollowStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) ViewCreatedPosts(ctx context.Context, in *FeedRequestMsg, opts ...grpc.CallOption) (*ListOfPosts, error) {
	out := new(ListOfPosts)
	err := c.cc.Invoke(ctx, "/socialpb.SocialService/ViewCreatedPosts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) ViewPersonalFeed(ctx context.Context, in *FeedRequestMsg, opts ...grpc.CallOption) (*ListOfPosts, error) {
	out := new(ListOfPosts)
	err := c.cc.Invoke(ctx, "/socialpb.SocialService/ViewPersonalFeed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SocialServiceServer is the server API for SocialService service.
type SocialServiceServer interface {
	CreatePost(context.Context, *PostMsg) (*PostMsg, error)
	DeletePost(context.Context, *PostMsg) (*Status, error)
	UpdateFollowStatus(context.Context, *FollowMapMsg) (*Status, error)
	ViewCreatedPosts(context.Context, *FeedRequestMsg) (*ListOfPosts, error)
	ViewPersonalFeed(context.Context, *FeedRequestMsg) (*ListOfPosts, error)
}

// UnimplementedSocialServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSocialServiceServer struct {
}

func (*UnimplementedSocialServiceServer) CreatePost(ctx context.Context, req *PostMsg) (*PostMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePost not implemented")
}
func (*UnimplementedSocialServiceServer) DeletePost(ctx context.Context, req *PostMsg) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePost not implemented")
}
func (*UnimplementedSocialServiceServer) UpdateFollowStatus(ctx context.Context, req *FollowMapMsg) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFollowStatus not implemented")
}
func (*UnimplementedSocialServiceServer) ViewCreatedPosts(ctx context.Context, req *FeedRequestMsg) (*ListOfPosts, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ViewCreatedPosts not implemented")
}
func (*UnimplementedSocialServiceServer) ViewPersonalFeed(ctx context.Context, req *FeedRequestMsg) (*ListOfPosts, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ViewPersonalFeed not implemented")
}

func RegisterSocialServiceServer(s *grpc.Server, srv SocialServiceServer) {
	s.RegisterService(&_SocialService_serviceDesc, srv)
}

func _SocialService_CreatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).CreatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/socialpb.SocialService/CreatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).CreatePost(ctx, req.(*PostMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_DeletePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).DeletePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/socialpb.SocialService/DeletePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).DeletePost(ctx, req.(*PostMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_UpdateFollowStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowMapMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).UpdateFollowStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/socialpb.SocialService/UpdateFollowStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).UpdateFollowStatus(ctx, req.(*FollowMapMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_ViewCreatedPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeedRequestMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).ViewCreatedPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/socialpb.SocialService/ViewCreatedPosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).ViewCreatedPosts(ctx, req.(*FeedRequestMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_ViewPersonalFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeedRequestMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).ViewPersonalFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/socialpb.SocialService/ViewPersonalFeed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).ViewPersonalFeed(ctx, req.(*FeedRequestMsg))
	}
	return interceptor(ctx, in, info, handler)
}

var _SocialService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "socialpb.SocialService",
	HandlerType: (*SocialServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePost",
			Handler:    _SocialService_CreatePost_Handler,
		},
		{
			MethodName: "DeletePost",
			Handler:    _SocialService_DeletePost_Handler,
		},
		{
			MethodName: "UpdateFollowStatus",
			Handler:    _SocialService_UpdateFollowStatus_Handler,
		},
		{
			MethodName: "ViewCreatedPosts",
			Handler:    _SocialService_ViewCreatedPosts_Handler,
		},
		{
			MethodName: "ViewPersonalFeed",
			Handler:    _SocialService_ViewPersonalFeed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "models.proto",
}
